name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX (XeLaTeX)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: apostila_github.tex
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: apostila-github
          path: apostila_github.pdf