name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup TeX Live
      run: sudo apt-get install -y texlive-full

    - name: Compile LaTeX
      run: latexmk -pdf main.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: apostila-github
        path: apostila_github.pdf