name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          latexmk \
          texlive-xetex \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-lang-portuguese

    - name: Compile LaTeX
      run: |
        latexmk -pdf -xelatex apostila_github.tex
        latexmk -c

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: apostila-github
        path: apostila_github.pdf
